#----------------------------------------------------------------------
# This file was generated by C:\Usr\Python36\lib\site-packages\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

catalog = {}
index = []

Colors = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAGlJ'
    b'REFUOI21k8EOgDAIQynstz353ToPBmOGAwxZr4P2wTaAhSpi77CfWy8ZlAg0PaJYQ6Cp4B0R'
    b'xZRAmyNhvEYv7cu0ZQrTI8wKvV2YHWRnf+rBYpzfJhGVWeJftTvlCN+8JRAQrfwLWV2J2y6k'
    b'rv/brwAAAABJRU5ErkJggg==')
index.append('Colors')
catalog['Colors'] = Colors

#----------------------------------------------------------------------
Colors2 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAJlJ'
    b'REFUWIXtlksOgCAMRC14bVaeW+pKFiRNP5AMi87SBB1fX41EpV7IFOjTVwpwb8y9MazArmQB'
    b'8m6BNHcqD0UKwAlkAbMD8+z/mUvXrYETuL0HorZLgRNQHYh+762k4ATMDmhvFCUFJyA6EN1v'
    b'7zk4AdWB3Xs/B05gOKBZLJHw2j/f5xwCqMAJjC3g/i7/41tCpZ7lQBbIAh806jBsqH1TIAAA'
    b'AABJRU5ErkJggg==')
index.append('Colors2')
catalog['Colors2'] = Colors2

#----------------------------------------------------------------------
copy = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAJdJ'
    b'REFUOI2lU9EOxCAIa3G/fTkv991n72FzTgebyUhIVKC2BEhLeGIEIDdgidMAUo9BchrEooAk'
    b'qPxcdi6D+ms7Z7/AvidW8gzI7huQRUuovksg2Xks7Q2V1y7NWkCdj8Dt/lnzDyAbPQx+ljDK'
    b'6STcMYjk2V3SCDzOzBINi8o6oV5DjyCLVxwle3YJUDt+nfNwG8NdmLU/IJKf+VxaPEIAAAAA'
    b'SUVORK5CYII=')
index.append('copy')
catalog['copy'] = copy

#----------------------------------------------------------------------
Copy_Big = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAANZJ'
    b'REFUWIXtl9EOgzAIRbnV317msv8WH6YmhdAWNaNmu0kfNCD0FNoKpIEilUKjExGIiF0OacCV'
    b'CfRDgLkMAsgnfhWJcAKj12EjBYCJzpMIJ6BqQK61fj/5AqR3kVB/BKoOeNHH/tlktz8bJMIJ'
    b'qC6QNaA1uQJspABauyYn0R+B+o4o1tboGsue50dGoj8C3hqwiFldIomEE1AJMHNxSAFoGs0J'
    b'fFt7AkdnUiNmkVMJRGn0nuc853fIetesfgaFeAJnP9B6ilq6LwG5ox1VOAH8/L/hP4EFBC9v'
    b'B/sWG1QAAAAASUVORK5CYII=')
index.append('Copy_Big')
catalog['Copy_Big'] = Copy_Big

#----------------------------------------------------------------------
Cut = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAHJJ'
    b'REFUOI2tk8EOwCAIQ1fcb3vyuyc7sTgHnQvjopjmtSQCSNkyJd6j9kNZ/wpIJ/gFYLFZ/BAA'
    b'KWD9UoIVdwowV+ZOAdqrjudnwOiuvWoE2iPnO6hdILu7CUwwi1ilP9JjhLkgDTaWlwzzNjKx'
    b'a5Bd5xOFyjcmz9rNVQAAAABJRU5ErkJggg==')
index.append('Cut')
catalog['Cut'] = Cut

#----------------------------------------------------------------------
Cut_Big = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAJ9J'
    b'REFUWIXtldEKgCAMAJv220LQd+t6qFEK4pzIlLyXkCFt55wAxm6aGNW/1ySAwSMGj9J4cwK9'
    b'WAmsBPbaDdTpYCx811LmMVCqmOK1zGMgpfXsCXUDIH0N09sgRd2AYA645+yPaA3m/NkteOfC'
    b'hvfXYRznGRnfQFpZjrRibm+MayBXAdcIF3UDKwHxHCCoR6adA8XXUFoZl/EN9EbdwAVc5ks+'
    b'URg8QAAAAABJRU5ErkJggg==')
index.append('Cut_Big')
catalog['Cut_Big'] = Cut_Big

#----------------------------------------------------------------------
JP_chapeau = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAGAAAABnCAYAAAD/nUeAAAAABHNCSVQICAgIfAhkiAAAIABJ'
    b'REFUeJzdvXmwZdtd3/dZ0x7OOffce/v2/AaN7yEhQAQx45jC5TixHRMPVfnD4JAUwkAVg4Sg'
    b'YhlDkQJCDJKY5yAhP0kg23Gq8l9SqZSTCmBhYikMJT09vbnf6+l23+kMe+815Y/f3vve7jdC'
    b'd+uJrKrTt+89097rt9Zv+P6+v99SOefMazTkixMJ0GgA1K1PErzHOtc/kQgpYrQiAZ/8k0/y'
    b'6cf+hJgjXdfRti0hBJRS6P6TlJLPtdayWq2YTqecOnWKM6d2+Ktf941oHClmjHF0XUdhHajx'
    b'Ko6HuuWybv/zX3jYO3z/HQ3FC2/o9mGdwwePc44MMvk5gdI88sgj7C92Wa6XHB0dsV6viTEC'
    b'jAKw1rFcLqmqCmMMRVEwn8/5+q/5Wv7q130jMUWsceScKYqC0Hm01mhj7um9D0N/Xr7lFS5B'
    b'99N1y2rq/xBiwDlHjB4fPJkMSvHT7/vnxORp25a2bfFeJs45h+knL+dM13XUdU1VVcQYSSkR'
    b'Y+TRRx/lkY89gtHDayMxym7TWhN8fNGrfcF13uF4TXfAqxlaazIJbQwZ2TE/9ws/x7Vr17h8'
    b'+TI3D3ZZt2u891hrsdYSYyTHBIBzBU3T4L0n54wxhsViQWEsV69eJeWEUXp8jgwohXWG4CPW'
    b'3dud8JrvgFdaUVnJRMbkUcAv/vIv8uQzT3Dz4AaHy0Ny/2alFDlnQgiklFBK4ZwjpUTXdaSU'
    b'qKoKrTWHh4dcv36dK1eu8KHf/mAvYMWqWRJiByrhg8cW914NveYCeLmRSWilWfs1Sms++Mhv'
    b'cfna8zS+4ebBTY6ODkgpYozBOYe1Fq3llnLOpJRIKVEUBSklDg4OWC6XFEWBUopnLj3Lpeef'
    b'5yMf/Qg+eOqqxlpLzhnn3OflHl97FfQSbkVGVn6IHaUryGQODw/Z39/n0qVL3Lhxg8msputa'
    b'lFLjA3q1FRMhBGJMaK0xxlCWJQDr9ZoOhVKGRz/3GYqiwFhLArq2EWEqQ0ppFOi9Gl+gOyD1'
    b'/yaU0SQiv/qbv8Izzz3D7t4uq9WC+dbGqPe11qSUaNuWruvIOYsno7VMrjHEKK5qjBGtNUop'
    b'2rZlb2+Pa7vX+dVf/1VC8lRlMV7FvZ58+EIRQOp/5tv/nIgp8pHf+Qif+9znuHLlCgcHBxhn'
    b'adsWrRUxxn6lx1HthBDw3t/i9QxCyTmTc+5tRmSxXvDkM09y+drz/Mt//a/oUkBpRSaNu/DF'
    b'xt3yhl5zFZRiRpv+VjSE0IHOZK1QKP7n/+Xf8Mk//iTXdq+xWBzSdOte1YjX0rYtQyyplBpX'
    b'rcpiB7z38tH9jhiMdUqJnDO2tNy4eZ3Lly+ztbWF1YamayhMIapL/f9cBQ2Tv16tAEYjqFF8'
    b'+KMf4vd///e5dOkSi8WCddv0qzqOq9xaizFm1P/DGAzwMNHDA7jlp1IZdOb5q8/zuSee4Jd+'
    b'7ZcpixJtNEkxur737P7v4We/qpEToKCeTsgkQvJoY/jwx36bP/x//pD9o328b2m6da/f06hm'
    b'uq7D9YHTSa9nUDFKqTEoG1RRCOH4eWtYNWtCCKzXa65dv8LujWt87OMfI+aIIsPLqKG7MV5z'
    b'FYTOxJjGiTLa8Bsf/E2eee7p0W08XBzRNA0xhlGNDB5K27bEGEcIYph43f+M8YU7ACCT0Uph'
    b'rSGrTCJycHjIY48/zuZ8Wz5r1PKCVt2T278nn/rnGLJKFSF5IPEbH/xNnr70FJ957DPs7++z'
    b'd3CT9XpNCH7U30NUO0ANJycfuMUYn9wNw+PFns85c7Q4oOs6nrvyHI888sjn5f5f8x0QQid6'
    b'XBt+64O/yRNPPMFjT3y2Vz2elAdfXPR8CgmS7JQYIsrcGgMMqkb1i92YW29xEFzKmUym7Tpm'
    b'8znL1YqdU6e4du0aKSVed/F1JNKI0t6r8RrvgISx4ud//H/6XZ557lkuXX6W1WqFtTJxg1eT'
    b'UiYE0eEDqim7R4zwyQgYGPX/oLLkM9Lomg62wjnHerkkpcRqtaKoBL749KOf5oMf/K0eLH95'
    b'l/ROxh0IIN32eIlXnfBCbn9fzIFAJJF46tkn+ezjj7Lu1hwuD0f3MXQRksIoi1EW50q0tqQE'
    b'ZVmKnk+ZEBMpgzYWYx1oTcyZkCKJW9UQQFJybaUrKF2BNZq2bWi7NUeLPa7vXeXpS0/wL37n'
    b't0lkfPb42JBJxNzjUzG+4J5e7bwM456roJPRZNu2WKtHg6uVJhF4/y99gM889hmUVezf2Gc2'
    b'm9F13bjabx+3uJw5gFKkGEWtpPSC1w3q6OS1DAsjdJ7E8QKJMdCROTo64PK1y0ynGyQiRhmy'
    b'SrRdS1UIpCHXdmc7Q93rjFhKCe/9CXcxopSiCy3aGj72Lx/hE3/0Cfb397l58yar1QqtNev1'
    b'GkASMTnfEvGeVCOAIKJJYleVj4OuQf3ofByknfSiUkpEjrEipRRFP7nExHw+54se+mLe+ta3'
    b'8s5veyegIPe7KGtyEqjkTsbnZQeUZdmrIZk8azXOOn73X3+cT37ykxweHnB4eDi6mcvlgs3N'
    b'Lbqupes8MQa8D3jfEUIkxkBKsm5CCLdEuHA82cPkDxM/5AustVhtUM6JJ6QZ8aQYBV3NOdO2'
    b'nt3dXZ5//nlSFrdVATEEUgRXFC9z569u3LkAXiFJKjlcQ0JWcOGK0aA99fQTNM2K67tXsaYg'
    b'E+m6FlTi8PCAdbNkvWrJRFlx/U+lM7rPZJXWjas3hNDnAyK+3yVWm1sMsrUFRSEPq0SNhJyI'
    b'UfIG3gfKssRph1KKK1euMJlM+NjHPsa3fsu3AmCsxRhNihFt7yxncM93gNGGtlvjnKNwlpg8'
    b'Rmse+egj3LhxgytXL4tK8g3Xr18fPZPVagHA1vZ8VBEnPZqcMzkpnLbjivXejyDc8P8BHc0x'
    b'4WPA+8i6bXDGoq2hntUAo1DG6DnL7prWMw4PD3n66acBxM7EiOKF8MdfZNiXNiJ3z0M1xqCV'
    b'BhJoTQI+98QT3Ny/QUiZg8MFi8WCup7IRVnL6TPncM6N3tA48fFWjCfGRNaKlATAM4XD4LBl'
    b'gfWezWJbhNG0tMGTfKKLAR8C3rdExJOZbswoigJtDNoacoSQkwirLXjuymU+8tGP8A//4bdi'
    b'rCXGjL5D/Q/3fAeknnUgkx9zQCnDhz/yIdpuzfXr19k/2mc6nXL69Gmm0+kYpa5WK06fPs3u'
    b'7u6L4jyD2jEmoZSW4Kt3M4cYIsZIVVV0XUfTNFQxkCP4EGibpk/mSw4h5jTugslkQmFLrLWk'
    b'LAmcdbtmd+8mKM26bajKyWgv7mS8jACGnaHHLxq8jpPg12DwBmxm+Cm+8hDFZuJoC+D69evs'
    b'7u5SVRUXZhdGT6LrRG0opZhUE0IXUFkJc0Ejz/XGVGtNylG87ZRwTm5lMMYxJ7TVTGYTbGcx'
    b'zuJDIKdETInJtBqFtlgs2Nvb6w2vwNud66iqirKoQWsOFkdcv3GdTKIoC9Z+Te3qF85aPyfD'
    b'dQx5iGFeQgjjAkkpoXKOL+uGpkTvmSyZTqf9RHUURcExSHX8U15/TLqSfyMazc/9wgf49Gcf'
    b'5ejogGeeeQZrNdd2r0MvgMHFzDljUOMFD/o/54xRx9STlCPaHqchxVb07m6vsqbTKUmoDuNi'
    b'GT5vSF0Oq9jHwN6NmxwcHY5Qd1nUTCYTLp6/j+3tHd7x5V/BO/+bd6LQtL6ldjUKaJqOqjr2'
    b'itq2HVOgcIxPAaPNUkphX1rXD6td/j+d1qzXS6y1/WpLYlyLCkUmxIA1ml/99V+jaVZcunSJ'
    b'nDNlWbJuVnRdx+HhPgcHBzzzzFMURUHTriiKY6/IWQvWyoX2un6IH1RGCFk5QwiE3tjGHFD6'
    b'GO2MWXEytFHmWDCDUE66pFVRUNc1m5ublJMJk6KgritWqxUhBCaTKSBMiul0yuXLzxMJGCyl'
    b'K2m7NWVRUlZyHz4IP8kWRuD1Piet1THZK/fCdta9XCB2HG6/UM+lfsItv/Lrv8K1a9doGvFi'
    b'vPfcuHGDwpWE6Fmv1zhnODo6IqUg9MHYsbW1xc3d3X4lB0gKZcAoEW7OCmI43lFZoUgoDNoA'
    b'WROTx8cOrUFrO171cRxg6HoUlT7JftKODF5V13WyG7RiPp8DYAvBhBSaejalchVlWfPwww9z'
    b'8cL9vPOd76R2NRpoepuQsrA4hrmRIQu87doRdBQhZBTqlQUwjM43YyhvjeH9H3g/Tz/7DHuH'
    b'e+zv74+r7saNG3RdhzUFnW8gHnN0QugI3uOcEXqIs5icyDmisybrjMGgVBYB5IhWFqWz+P8k'
    b'tLIYq9DKgkoYo1BaEjspiasZo+A/5OPdHVHHKOiJW44xkhRUVSUucFnQti0oRRcDZVnTdh7f'
    b'dkwmM7a3dzh//jxve9vb+Kf/7T8jhI7CFoAaJ5VRKNUogJjyOPkgqr23Aa8sgKZd9R8Gv/4b'
    b'v8ajjz7K/v4+V65dZndvF1s4DvcPiDGysbFJ13UsFgum0ymx81gr0IIxZlD3NM0ap2BzUqN7'
    b'sAyOdWUOEkg5a2/xt606jmq11hh9DLBleg2Vj6/dd5GYxTbFPFimPEIX2poekhBSF0oRyRhn'
    b'UVoTo+SerXUkwCpLNZ1xevsUp0+fZnt7m5wV29vbTKdTvu97vl++N3icdXQ+9Gy9jLOOtmtF'
    b'raohd52G+P3FBSCBkxkn/1Of+hRPP/00e3s3iDmxDo340j0VUKl+i/WZKKeNqCErqmW1WolH'
    b'oOB1912kygl9W+42pSTgWkqkEG/BdgxqhKOdc0zqso8HTjAiQg9dpNijpSKAAXRLgEoy0UJ7'
    b'6SN2Y8gKsla0XTe+39iCECK2cGgMrijQGCazqXhskwlt23Lx4kXqesp8PufC+Yu86/vfBWja'
    b'rhVvCkZvEMD72LuhLxrQiVeTkxrt9KOPfZbPPfE4y+UR67Yh5CAXXgil+2SmavBYmmZNYTRt'
    b'uxY3r1lTliX3nb9A5SxTa8i+wfvBhdOobACH6iPYk3h+CIEYIj4GsrcQelZEOnb9dEqYKAY7'
    b'5IhGyd0o0H38YJUlK0WXgkDXUWOcpfEdxhqcKsbd0HYB7Sw5CotiuVgw39hif3+forAcHOzh'
    b'XMnjjz9OWZZsb+/w1FNPcem5Z5lOZly8eJHv+I7vFGHqYbdmnDOvhIaKA9f5hg996EP8r//7'
    b'/8blq1cIsWP/8BDrdO+tQBhZCMdZJ5X6WIGESpHQrVEpct/F82zONpiUBaXK+G5FCnlUKyoJ'
    b'K8IYQ/LHRnPgfoYQ5Hmn0YUmRolwLZrSlj1ymsBoYkpkJQwH6D0g1XtVKRGN6PpB/xtjiD0o'
    b'FzWsmpZ129F2gaQNZT0hoWhaT13XQDqmxGsNRjyuYYcWRcGb3vQmzp29wD/74R9B5YxWdjTY'
    b'rxAJyy4oXMVTzz7D0XJB0zRc3b3KdEMiwdiJ3x7SgLFzyy5wWoth6iexcI5pVVMXDmc0OQaM'
    b'diibxgi3KCyFdVilif4YeiBHotEEIzGBQJ1ynSaBRaFVRpExRqOcJWsjyZdeAAYp3tAp41Ok'
    b'I1EZeyKZD85oggKfI5OiFA8ptewvlrQ+4KqanKGLAcMx0QsGLlJLCN2IBP+H//BHvP71b+S9'
    b'//Sf8NAb38y3f/u3i3dnXlEAx2O1WvXMhMjZs2dPJEz6NKAeIr9jAQCEtpVJyRmdFYWrmEwm'
    b'lGUBMdF0AaPkfTEmFBntLFpbtNLUG5bUG2SV4wnOp5do20mUiQWbFTprkkkY4zCFI/arPzJA'
    b'1RmdBVLOAVLSgv30OYecZScqY1BJY42mrCoylt39A5qmYYLCGEds2zHXoKx8t0q9t9U7FjHL'
    b'Dr58+TI3b97k2rVrLJsV7/qe7wfSKwtADEjJbDajWYkAFmtBKmOMFD2RKqVh0tUtKkijsEqB'
    b'0mAMhbWURYExjhAaZrMNYgyoBForKldQuQJnrcDFKLQzoBIahcqR6D0hWLk5I9EyCZwxoy0w'
    b'tkA7i88y+ZHcU9kTKoPxBnUijzwwJIbftTFYrYhJUVYlSTvqm3usDg4I3ouqjQrTR9gkLcLt'
    b'YwtljhM/IQQODg6o65rn0nNorfnFX/pFvvd7vveVBVD2GaKjoyO2t7dZXV5hMGAkWxW6RiY7'
    b'K8FZ8vFOICYKazEqk1Ls3US5SdsLRGtNtxaYuCwdUSe63Em2yRpAYYymNE5c2KxRRhOj7XW4'
    b'eFlKS6yhETTT2IJIxmpFyAmfxB0dvLRoNNlqVMys23bEakaXt/89ozBaM6lq5rMZh4sFXddh'
    b'LGhbyO5RSRyGTP8dCt3/bJqG2WzGarUmkVku1lhr2djYIL6aHZCRrflFb/4inn76abz3zGYz'
    b'bh7cvI2VNoB0anQp6d+bUyQGj4qe7Kx4Ni6N3M7FqqHrOrpQSpFdBmcNk7KiNJboLGBxSuOM'
    b'RjtNkWWCY4LoAxpNVVUoJQJQ2tIGLx5eFEPZBS+cU6VQSa6t9ZI7iD1Idgu7ImdMn3AxVlGW'
    b'JcYYfIgQM8rkMSOntZKAkUF+MgfT6ZSjoyMmk1mP4Gr29vZ47LHH+JEf/ZFXFoDGkHXmu7/7'
    b'u/mDP/wDtre32dvbw2kHKZHy4L/3edb+54DlGNMjgVmwnsI6dKa3IZ7dgz3WjazAdWo5auT1'
    b'BoWzho3JlMIZJoWTR1UyqStKY9AZjAKjTB8sWXIfqKEyIXnWrWfdtSzWK5quJZJPUF0SwSdi'
    b'zJBkIktn+2KPAqU1xjqSyAKr5Tt0GhL4EVBYC2iFykq4pkBCk8kcHC2Zz+csj46YTCY0TUPh'
    b'C0IIXLt27dUZYY0BlTlz6gxPPvkkdV3Tti1Nu8I5MwpAKcUYhGZhI0zrkhQ1KhqqHvwiR9pV'
    b'x2q1wqjMrCpQVlKAMfSpwRAITWC5WlNoTeUss0nFqfkGOStimbBZ4U7kAhKZFCMhRrIWjOfo'
    b'aMGqWXN4dMRivRLH2mgUA7ze6+wsBrguCzY2NiiKCmvEGAOkHjsSIWRS1vgQKIoSpU7A8z38'
    b'nHv9XxQFBwcHTOuanKUSc4jk9/f3X4UK6r0DYzUPPvggjz/1+IibW2tJKWKtxfdb2dlSvI6c'
    b'MFZWkzKaQldUVnN6a5PZbEbqOurCYbWkA11ZE1JkvW57vEY8r6F0tNCG9WrJ8rDh8OaC0hrO'
    b'nT3NpChRRhNSZLFa4sqS5XpFCInDxYLWBxaLBRlNWdY0TUMKGecsQafRUJ5M4nTrBqs0dmMO'
    b'MVHVNe2YMxaIYdWGHt8KskhVL8g+7MvIZ3vvKcuy1waGGAQvmkwmPPTQQ68sgCHDtFwvePe7'
    b'3s2zzz47uqSHiz4B3nsFA2o6BCZ16WTyXH8hpsQ5g9OaZDS2sJztOflZgc+wUU/wUVKNW/NN'
    b'mqbDTDVVUaBjpHCOm7u7XH72Ejeu7rIxqwSQM5qQEllBGzynd84y3ZhxZjKjaVtWq4Z153s1'
    b'ObiOBltYKXFFcr2xaUbPZXV0iClKQs5oV7AxlbRlwFCWhjDQYm4D+G4f1lqann6vlWUymbCz'
    b's8NP/PhPvIwAhkr1nioyrWfEHPjA+z/At3zbt7BarWjbhnUXRhfUGIPq3VBrDFVVsV6ucKbg'
    b'6PAQkzzkbXIKlJUTgShwWhH78lDjDFolmuzJSaG1pSxKQueJbYtvZdtfuHCR7c0Zq+UB9KVM'
    b'MWcCitZ3zOYbTDdm+C5SljUhQFIaLe4LCVEHxmlyijijsVoT1mtBQ/sJXbYdR0eHtCHRJGFe'
    b'RAVlVZPaDvrEkeqRwKx7SEWL4SiKgq5pKFwlYNy6xWrL/fc/AKhX3gHD1myahqqqSEQeftPD'
    b'7O3t0TSNrNzQjrVXMRwjkSEEjBaot3EikI3JlLqyTKuSSV0ydSUHBwfsHx5x8/CIvaMFjQ+E'
    b'JOVHTee5cO48ThsMGZNBZwHrNoEzO6eRYqZMlyIBJXT2rmV5tcG5kqyNlKpm6HJkOptS1xVl'
    b'WWI15BhIMaBiICCOU+HExXRFhVk3LG/skbKmtI6WvvbMFazX634HHO8GidrTOG+iomX3bWxs'
    b'jJpCvagAbttJvg24wo5lmwrFe9/7Xr7n+7+HGzduEFLPVsuZGI7zxDFGDg8PsQpynDKb1pw5'
    b'tc3mfIZWWXAkrXj88iWeu3yFlBWmrDhMgcN2hS1KolFMdjYJlWW1WmJQFFpRO4d2lmgUhbFM'
    b'CofXsGhWhFZqglWyhByJvmO1bmlDIMTMld0bzDY22djexhrN+dPbbG/MKIua0mjSpGZxdCRC'
    b'SciOLEoOVw3ZJ2azObFphONU1fi2EeLwQH+UrdDXeyuMdjjriD7iW0/nAvfdt8OD9z3Y9wh4'
    b'heGKY5Zy13XQr46dnR0uXLiA1eYYpex1v9UGq/UIJaeUmM1mbG7NexugICW6rmVv74CDwwXa'
    b'Fpy7eB/nL16kns5ISMBV1tVYDRNCh0qJHAN16TA5kTpPaDuyDxDSWBs2PELMdDFibEE5ndGl'
    b'zGGzZvfwkMs3dnn0sc9y9epVrl+/3tcQC1TijCFncTBsX2XZNJKUqqqK4ONogE/agBFTOhHU'
    b'HR0dYYxhPp9T1zUXLlzgu77ru2SuXkkAwUesNSh9TPcA+Kkf/yne/UPvJgTP5cuX2ev9flIW'
    b'5oIzGAVbmxtYa9je3GJrvtkHI5EUE6HpKHXB+e3zFHWNajO1LtmZbBGS6O7JpKJbrXGmwMRI'
    b'0QVciJze3GJeVtQZso/klCitQ1nH4WopOYHgOTw6xOdMPTXMphO2dnbAOlRhMQrOzadsbm5y'
    b'9cplDvdv8rqL91OVjslkQjWZgHKsvGc2m3DYNHRth+ld5uMcRkT16OaI3acewU2JqijF5TaG'
    b'c6fPcN/5C9TV9NUJYOiVMNApWt/09MLMz/7Mz/ID73kXOYOPkXVvwGL0WG0pSotRidQFSmuo'
    b'S0dOEnUuj45YHBxRFVPuO3sRtGHRrCknE+ZVRRdk9a3XS1IKTKyhKhwTW6BTZF5NKIDSFfjY'
    b'Iu69waeIb1t8zCitqKuCWhkB41KktpqoMr7rqCc1F3fOsFnXPN89w3q1IJxZoypNJPcBoWbi'
    b'HA+cu0DTBC5fexKvFDFmqukElfPIvh52w/EvmhgD8/kmWrfURckb3vAGfviHf1ieJr+IAF6C'
    b'bTes/tJVJ16W+Nn3/xzv+aEfxBjHY099jnXXoo2i8Q0z7TBJk7uWgsC8Klg3ng4IwPbZ0xRZ'
    b'k9Iaoy3z2tIFT0gBcmR1dCD8y9wxqRzz6YzaFdRWOP2mTzUq67BakZWmUor7z56n7TqihoOj'
    b'JU3XgoJJCrz5wjnZqUpR2AK9WLNaNDxw7hwhbtKsF7ThCDutmVZTSgUmGjSZi5vbPOEuUTrN'
    b'9sYmGxtznnr+Esk6lusVSkkuwTrJSWTo2daajckGp7Z2eMPrXo9G0bWSmLpDZpzkC97/M+/j'
    b'XT/0HlCKzz75GOvVESF6YpeYndrkcLHP7pXLfNlDbyZ1lmW74NTmKVL0WCB1LaEJY9CXyFgU'
    b'tdNkq5hPSgpbUhqLw1IYJ6TbqNA6owx9KlFTWSOF3GVJ7FViYTU+RpzOTBRCW7SW0lWopDFG'
    b'E5SnCdB2gUAgEfEEWCd26gplDLUrQAUUmvvP7nD+3EUmGzM+9ek/o2kayqnGGknuL5uGyWQy'
    b'xkfnz57jHe94Bz/wAz8w5j0ksXSHI/TczZ/9mffzwAMP8NaHHmZaTZnVM8qi4PyZs7z1i76Y'
    b'zcmMrm2xSlEag8mJWVkzcSVWS7LeGoU1itJoaueYVhWVK9jamLM126CwjsIZSmckUtWG0hVU'
    b'zkow1iMw8hphT5w6tcWpU1vMZzMxrESBtlUm5SBQtwFtwGmN0waNwreBxeGyj9ILsgJbWiZ1'
    b'iVHQNWuuXnkeozQhSC2B1np0N6211HXNfD5ne3ubhx9+mJ/4iZ8YHRWp9P9zJGRedGTpSNW1'
    b'LVkrfvHnfoF3v+fdNKsVVy89TVgtICm25nPcdEKhDKZyTIqSa9d3QWmsVpTGonqa+VjLi/B0'
    b'ok7UtoAIKSaMFnpKTBlLRinTo5uQQiBphVJWotoQmNR1j+E41m0DKUvUm7MkdcYKy4g2illV'
    b'U1GwyokQBEX1qW9d04FVio3phFPzOdunT/P4leuC4BpN9JGEfJdzjm7dsLE94/4LF/n5n//5'
    b'W6ZuQJLvAgVai3pwFRr4mf/hn/MffdmX8/oHXs+Fc+c5tbVF6CLTumZ7cxOHZuJKdjbmmJiJ'
    b'nScFj0kJh2S1bFY4raisYWs2wwKxa9Ex4pSGkMi+Q4/vj+gkCfwUIzlEFGCUxq8bjFJM65KN'
    b'6YSNac1sUjOpCqrC9qQu2TkqBlIXoEtoDybBrJ6AVri6oAstbbNCxY7F0R6+J/jGGGnW3dix'
    b'K8bIpKyYb2yxubnJ2972tj5XfsKT1Iou+LvDQR/UkEJTuIr//id/kre//e287sHXM59tsrO1'
    b'TVVOMEqjlSI0LRv1hNJodJLJI0Ri78+bDKW2lNpiUaTOQ4hU1lHZgqoomLiSqihx2sjDWCrr'
    b'5D1Kj4/oAypmnLHUzlFYKw3SomTW6tIyqUrqqqDUFpfAZcW8rDk93xLqZI69mkpMasfWxozS'
    b'yE482NsXKLxnWwx5caMdZ06f5hu+9uv4wR/8QZmfPi7w3qNQOOvuUAX1XfdsT0JdNWvqqqZr'
    b'Az/24z8JKfDbP/8Brj77JGUS4m1dlKy6jq5ZQ4iilowEUIqMGThASpNiYr1YsO5aSltQl2IT'
    b'SBlrJVOlrEHnLICZFvcxaiQD1jcbUDmRfb/ashTiJS/ww43FgbS1QdKfVmmKsqSyJbauAIWy'
    b'lkQUfz8GbIxMy4KNuhopkCkCKlNPa7ZObbO5scVXf/VX86M/+mMCa/ffjdI4VxKS72HwOyzS'
    b'G2np+bjboyJB8GCA0PJrP/Xj+MURUwe+aVAh0DUNoWshC6lrLKDrU45dkOKI1aohpsR8Nmd7'
    b'awuDIceEQ3ZPoY1k3FImKkhGkXKmiZ42eJqukcSKMUJp1JK7HSpmku7bHoREoQ1VUQqr2Tqi'
    b'UaiyxJNYti1N1/Dss8+yNd9kezKjwfB///Fn+fSl55hONphtzZnNN7m8AYnrAAAUKUlEQVRw'
    b'30W++C1v473vfS9OO9lx/QQNCSxt1EvEAX/OIXlTmfzjigKNsg5y3yrGWYq6AiKoli4IXTF0'
    b'UBcl5ERKA13b4lMkhUDssfwzZ84wm82k/qtvshdiQJEwffrSWI1PkYAEYDoqiAnXU07WK2ld'
    b'KTBCJxRHpehSxCqFc5ZCCRVGRyEKKxQpBkxhqOuKGANnt3c4tb1N7DxOWbwPbM63mUymnD13'
    b'nre87Ut430+/7xjyHgKrE8xs6DcDd6FC5mT59QtGn3g3RU+Wape9O1egfWQ6naJiQCuD6gld'
    b'CiMlR+uG1WrFfD6nrCqMs5Ay0Se8byFlKuNY+jWltShriSkRchIU04kn0nQtkGnXS7ExzuIU'
    b'6L5Zh7ECMtrceyRZsls6JJkzLZWWIXSCDaGInWcymRJaKY+6cOEC99//AG96+CHe854fkolW'
    b'WhBW8/JTfBdKlF6qk4hGVrxmMt9kmTy+VaQM1mhC65mWBdmDOVEimrMiB2nCsVqtOL99Cu0c'
    b'XZ+qJAJZ6C4qBZxWdClBDGhr0KqQjFyIhOT7hn3CJ+p8Ry4LbNmrBaXH4hDVszkUxyCaypCJ'
    b'uKJEJ818NsPjuHbtOsoUYGsuXrif8298Mz/90++jqIQN3cWAM8etcl6u4dAdC0DssDS1eKEo'
    b'RC9tnznL8uAmyShhI3dJiFxKyLwDli6lppHlesWqaQgpc7RakY0Y6hADxjistiQfOFo3THrG'
    b'tVEWorSdSUk6PBhj6EJC9ZBF264JYcK0rrB6aFkwXLUiKUXSmqTEGOc+XbpuGrQ2dI2HDNPJ'
    b'JhunztDZgi+ZnuKf/Nh/hyuk5MlHjyvKF7Rg5uTvJ+Ceu1KkN3yepm8LcLKTQE488MADXHry'
    b'syjjUCYQcktd9rq/p42Ahr6g4uhoyappUVrTec/Ng318THRtADTOWMqyZFaVLJOn0A5C4HD/'
    b'iJs392m7js3NTU7tbPWu73GR38mqS2nYqslKNpZSmqRVX6wh1TUDrl+WJV0X2NrcZrG8xnT7'
    b'NN/5fd8PpgZlxkKWmI8XYc639cJ+EZztDgVwa0MKNXz1+GUaZQve8MY38ak/+gRxvSJrRUhC'
    b'P0y+o+cyontqY9d1LFYrOu+xZYGyhuW6YbFc0wZP20jt76mtLR68/wFmRUlUQhI4WC64uZD6'
    b'ri5HuhjYms8wCmHBGXucWDflGImmvgVfUsKYSAOWbzTGaeazKU8/f5mN6Rb7e4ds7ZzlW7/3'
    b'+8A6msWKarYxFoo7W4inkwRWeaV+Z3e/Uv7k33uJT7a2hKB0U/ByO9SBDVRAJbz5tm05XCzE'
    b'cBpDWVckBaYsmLmCDaVoW8/h4SFdSNzYu0ne2oQcCT6hq4ozF84f15SlhO9bnNVFgY2Opm2l'
    b'zLRwwudUSlZqTyXJRoNBGHHGkLTi+vXrbG5u0jaSIn3jF7+hvzlNNRNcP8aMc4U0OUvifcWY'
    b'hY5+z2xAfoVAOmty6FB9h5SUAlpn6romti3WGHIMqJTpQmC5XLJYLQkx40qLrSqSlsRO1wba'
    b'4CnqglP2FE3TsFyvSSkIEKfEe6pcMdJA2nUjeFLSmKJAdR1tXNH6jpCFQSHNN6SUVjJZoIxB'
    b'K4U2ipASW1tb7C8bnKs4c98pNk6dAVuSspBQvO9wRTXe9mDEzbAD+oBVnrybAlC3CUGdMMP9'
    b'FyptAYmCnTOSGyWgLMQ2YVImRcgh47tI03qSURSTCa6eSK+evttKURTC26HFqQo9ndBFaUWA'
    b'kvSpdUUfHWtqPUErgSHa4CmqkmbpaLpE00W0idTWyJwohVGDEJQUbWj53a8jeLCzms1T5zlz'
    b'/wOQh/cZ3Ike0wpJyd7yhxf5//Dfu1cpr4Z579lmw9+1lWg3ZYmQAaUzKimpWBm8kSSHMyyb'
    b'NbPtTVwp/Z5NX4CdjUAPxEChEJpKTmgtbufJhhwjO5tjloJGCuWSUax9wKdMRqjryqhxLY3Z'
    b'LZ1JSvIDZTWj1AURxc6FC3zZV32V3KPSL5nAeqn5uX3cxVYFg0G+TS31N3Syvw8cJ7K7GKR8'
    b'NQaaIM2TNre2KOuarBRaG4yS2jCx6xqboPUJH6SGVfX9HYwxoI6baGgUmb5EqaeyWOeEVhk8'
    b'VY444XoLaVervugjE5W4yVFBEzzlZE49P0U1m0E1EUwpZ1EzdzA+P0378rEbSIroDLmvUEkp'
    b'Ekk0KbDyLZP5BpPZFLQZC6yHyVchSfFfqSmzxrtA6yVJPlAgB3q8MN/AmIIUIkoJdF1Ma9Zd'
    b'i8+RLkXK3O9Ya9BGSmWTFp5pTApXViRlMWXF2Yv38Q1//T+RbaI0+s7mHrhbArjlQvpVroZ+'
    b'Bf3OUH2xnVLi/2epckn9Kuuy0Md3Tp/tybNKslHaCeOsk8pHgqzoSVECJbGq0dZiCwdajX2C'
    b'0EI9DCFIcUbOqLJAOc2yWZO0IirwJIxKUvxt++tTELNQJUmZajrl3AMP8E1/55vpW3KRgXXn'
    b'qQv3qrXQi407F8Cr+nbV12YlqdU9CcBqRYqZ0KuH+fZWT220FNayOFwQOk+3bghNS+oCVksw'
    b'VhiLLQuMCaQQpKzIaAHnnENbQ9CKiBUOj4YQjJQcaUVWUoQo6kcLWqmlJUICYlYobTl78T7+'
    b'xn/x98E6UI7Od2hnKIs7P2PgLtuAFwn3+rkejKEcLxIgCqVdWHUC0W5tbWGMYr1uUCmze3TI'
    b'3o09aaznE05JM22fMk0+Jg6DxBL0PRqKqsRVJdYJv8c6S8p9x5cYKdzQPcuCVvJQGenWLlX1'
    b'MUssUBQVh8s1uBp8JCqFK2oiipAzxR02bfq8NW4diiFCCJiYewEcF2YrpaRb4rphdbRghebq'
    b'5SvSkCkmKlcxm2+yUU96VNT3/efs2Bmra1toM7ZtMGs3Bnz1pMJ3HVQlyXdjqaqUNInaSfSO'
    b'AcOaUX21TUE1mYlqsnISU0IJ5mO+oHbASwylefRTf0Lb+jHhHoLHYccJTCmxMZugSATvaZuG'
    b'5XKJsYrTp8+yc+oUZVHRrRucKUghsFos2ZhImlMZ6cbYBWkOsmzWdF3Ler0iBE9VFX33xUjp'
    b'pDolxyTBVl9RM/SRkI66ClPUpARN45nPT0GWRJAazhsryle+91cxPi874E0PvZk/+sS/RbsC'
    b'W5TknPCNVNWnIM1TlVKs24amkSNEHnjgAba3tykLqSxpmpZuEVit5ESk6AOmLDBKoZJCO005'
    b'qZnONzjd932Qzi3X6bqu7z8dsFtbVIW0N9DKoqwU8amoyEpsUUSBDkTl2JjNuXFzT9xbqyEp'
    b'qqKUMtTjdMtfeNw9LOj2Kznxdzudjr5524ohVRms1mjySEfxbUeOAdfXe6WUuHnzZt8CAbrQ'
    b'pxnXa5p1x7LtmFTSZqym7PGc3PfrcRSVYzZ/vRQCHh2MtEHBikRIZTnFxw4QbmfOwm1NGZQ2'
    b'5KyYTbfkRpTBdx2uLFBDLZb6Au+aCEDMnLtwkcXBLvshkkLEJBDvKJOSIJQxJzl0bVKjtWW5'
    b'XJKi9GyjJz11nR9Z01prFuuVJPyJtMGjjXRjn5TVeGyVc46iLMdD36wdCvGk1jgipUUSbCiM'
    b'K4mCR+ND4kve/uWAtKl0pXQKU2PI/FIJqVc37qIATrYuE4xdDRYtRr707W/n0tOfpZ5OaMks'
    b'DxZCJ1GSGvTBS65YG0KKPdcz0QVPF1pA07YdXRuEudx3SZltTEgp9JegpBmHkTIlv/IjXTwi'
    b'XRV9lCNSClOiCksbk6QiyKQs3o/WiuCjNBV53et48KGHQMnugqEXKndBAX0edkDOoMqSsw++'
    b'npgV2hYo09J2ATeVLitd6GiDH2uumqYZOTaxr3w4LhAxI6sshI5h9Q21ulL1HiXi1lr4mUgj'
    b'qKx6SEQrPAm6Voi9xhJTkAAR+ut03Hf//XzlV3+tpC0zPZNhqIeOt/Qx+ouOu7wDTv6UMWaF'
    b'FJw+fZqD3ct478fGdV2WQo0QA65wo0HOQ/O+vs5YXM+A7zypb5xqrMJ30rJMhNKXytK3Ry4K'
    b'mm4tK1bZvqqdHmYQWMQkSYmmGLBWSxJdKzY3NvmKr/wqzr/hjeIya9nfMWUpMBmJPnc27nok'
    b'PPyakeBIW6TtQM48/EVv4dJTj7MXdiXXul5R15WAF1oadMQMoZVTMZyWyVFKUZSWstxkOpW+'
    b'EEopqqrCOjMeYzugoTFJ7mG1btEGUspoR9+YqeflWGkMkmOHIfZ942qSMihVMN3c4f63fmmP'
    b'L5sxeO9ZJcfZvzscdzkS7n9mLZAP4HOSJHoKXN9bEIOmJxwSQpIUQpS3JS0E3JQV2rgxMVJp'
    b'aXNjrYZUEL2cnudMRiVPXZdATReStBFQkmLMJHLKKCPtxhQKtCGnROcjObfUTkNURJ/oXMa4'
    b'gnKyzTu+7hvlunpsf7gfM676F9/xf95xx2I8jhxP/EEdw85yRgCkrPiyr/hKYqbvt6PGKNa5'
    b'AucKpCO6wrlCerT1/dqEOdF3z8rxmFWcIikGYuiIPox95kBQVGsKtHUorcfuJXl4DAhtjqCk'
    b'p0PXBkxZo13FG97yNnCVGF+kDvNW9tOJcqQ7GPfACOsXQEKJhDWOzc1NHnzjm3juscD1gyO6'
    b'lPGhE6+j74RVuYKqqmTFVyW5Rz+l8cfQHElu3Edp7qf14J30Nqf3hqzWRCJZZZTOxJyPGQsI'
    b'3o/StF1EJQ+mIGbFxuaWrH534p5eQD1LJ567o9m6R6M3viknNJbOd2AL/tpf/xts7pxhduoU'
    b'rp5gy4qspYB6Npsx2Zgx9PJMKY3N/3Kkb4eQCQF8QLCljDyS1AonpfuJVWAYG7dyovHfUMEY'
    b's+Lm4bKvnoSinlFPZ/ztv/PNYE0/x/duiu79pwMGqUQvnLDGti7cx1d+/deDK6k2tuhSZtl2'
    b'HK7XLHu+/VBhYozBez+WwAYfaX2g9YEuZEKEjCagiFo4PWg19iUaU5Mn2onlrOSBPGbzLW7s'
    b'H5FNQVHP+Lv/4L9ksnMGjBEP4h6POxLAizph+daHgt6X1zStVDN+8Vd9DV/6FV+FKitm26cp'
    b'p3MwJcs2cLBYEQBtrJwRn+XQnJhyDx0bstJSQWMtASUBFFk6lOR8W4MmNfYIGmrQ4tDdSxtW'
    b'rUe5imIy48z5C5x705vFfVOGtmle9B7vQiJsHPdAxLeG5jlBWVhCzFhTyCQS+Jt//+/hSfzp'
    b'H/+/LFuPbjwJRUiRqGRiF02D01KDpfueQILTyBlgSsibPW9/OMZE6CYaaaNmdX/sSAw0bUPX'
    b'BTIKawt01nQps7Uxp5rM+Vvf/HchGzCWGBJlXfUG+PiOjplu+rY//MXGHdcH3IrFpePVf+IU'
    b'0qYJlLXIOvgW5wajlrh++TL//t/9AZ/+0z/lyvOX2Lt+Bac1G3WFb5d9HweJOouiwJpCdH2f'
    b'Q9CqX8351tM1rLUY11+DkaqU1WrFetWQtaEsanRRM53P2dg+zX/2n/5tvuKvfCNoKwczOUvn'
    b'I6avk+5bPH2BC2DMAcMLIuJbODHhlneGpsWWBZ/8xO/xb/7Vxzm4sYuKHSl2kAJts6IsBYc3'
    b'xoz9PZvVmtKWI96TkxrTndZqtO3pjtFLsJYSi6MVpigp3ARjHWcuvo7/+p3/mDe/+WFUPQUs'
    b'vgu4Ug5vGK77L4cAgFEA+aUFIKMH0DhRvpMEKPvE//l/8JEPf5C9m9dwWtO1a1yhxhOYhm7n'
    b's8l0bOyah7b1KY/pRmMVq9WiT9hIQLZuOlLSbJ/a4dyFB/jP/94/4B1f/XXi8ydAW0KUE/7y'
    b'LQJIt97nXRLAXaGnv+yTA0NuyA33b0h9INP5RGklcg5J4ZTha/7KN+Fj4nd/5yNcv3qF1brF'
    b'BkUMHdYKNlRYTVwmUuiZdf2hdkYprO0FYBSuqPApYksn0ERRc2bnNJtbp2Xyv+brwRWQxbZo'
    b'pH7h9nj3Xo17cJDbcF7FiUs/+Q0nuKqDces7B4w8m5wCOXY88cRn+Z1H/gWfefTP2N+7Ttus'
    b'hQgVw0g5N31eVmctBKyhr5sbTsoQemTM0iR25/Q5yumcd377d/L2r/1awPZ2y5JQ4zUILH3r'
    b'ffWX31/kF4gKOhn1ygelE17DCYribUIY/tSuA1VlRyEoPRwaIajm5Wef5eMf/yj//g//gMXh'
    b'PjoHVosjVE5Yp2laQVbN0LMtD6fpMR5XIgw3zXRji6Kc8g3f+E18xz/+LjAloPqGgwK4pSju'
    b'f0q3CkDdpcj39nHXBZBuC9n1IITbv0Xdait8EPJuytLC2FrdF+QBRH7v//q3/I+/9stcfv5Z'
    b'KquIIaAULNrlyHIAJHLuoeycI7PZjNZHsrVsnzrDV37NN/Dt7/xOtnbO4UPA2XK80iSIHS8G'
    b'898rAdyTUO+l0sS3PDH8P3owBtdDvkqJByNltwIrtE3DN/zH30QKkQ//1m/w7FOPc2prm6PF'
    b'nnSw6o9A0RlMIcmS4UCg5bqlqEp0UfDmhx7iH33bt7G1cxoQ0pVUbFpS7JnRJy56uJ57OV67'
    b'HXDidbHrMEUFSvAe3etukEmQSUmkrqVbL/jjT32Sf/cHv8dzz13i0uWn6XqOkNFa2tiMPSc6'
    b'Wh8oioL77n+Q7/uB9/D6Nz4MWLounjgLUnabFOhBCNJw9uTkf+GqoNvGCzTNi71AvZoX9i8/'
    b'cXljIjwncgjEFPj0p/+Mpy89y9WrVymMZWdnh42NDVarFdevX+Wxxx4npcS3/Ff/iLe85S1I'
    b'9bjqjxg5Vj+v1bjnx9nejXGyH9swBra1tXKa0sm2mSDtNtu2ZXd3F6UUDz7woHxWL/mc5SxK'
    b'cxfYbXcy/lIIAF5cCDJetER8fM/J1w+Hs+V83D/6tVz98Hnkht7LcdytXcbJc8+GXncDjHE3'
    b'mAx3c/yl2QF3OoamInCcK9D6tV398FrvvzsYJxMuJ0ufTu6G4e/e+3Gy27Yd+3p+IYwvjKv4'
    b'c45bPSN1Sw/P4ffhuZzzSOqCY/X0hbLx/z+aaaBOpUUMwQAAAABJRU5ErkJggg==')
index.append('JP-chapeau')
catalog['JP-chapeau'] = JP_chapeau

#----------------------------------------------------------------------
New = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAF1J'
    b'REFUOI3tkzEOwDAIA22S//84cYe2QxGJqFg61BMDOhsBpDVU1O9Cc2jXSGvcAgBAihkkoTkU'
    b'QSyV84JHKdMA8jT3kB52B+4e9DrBSj/gC4DHHfgdZ8TqN5ZHOACokRkohSNQfwAAAABJRU5E'
    b'rkJggg==')
index.append('New')
catalog['New'] = New

#----------------------------------------------------------------------
New_Big = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAHZJ'
    b'REFUWIXtl0sKwCAMRDOx979xmy5KNgHx00LEzixF4vMRUQEtkhlNXV1Ejjhg12lvCkILRuav'
    b'Z8BjNiYCeDbuBntNrGtgNm4OQJeJ/Qx4L3haPbGPgdqpiUZi0g0QgAAEIAABCECA6nugdY9/'
    b'lXQD+P3fkAA3ODEWY1FLXIQAAAAASUVORK5CYII=')
index.append('New_Big')
catalog['New_Big'] = New_Big

#----------------------------------------------------------------------
OpenFolder = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAKNJ'
    b'REFUOI2lk+EOgyAMhA/ktbe223Pr+WOrAawT3SVNIJTrR4GU8oR/VOqJPB/sE+z1Tj8dUp6Q'
    b'8gRVZSRVpedEUbyyiADYFxMhAOzInK5ECx2jm7SbzcBlZj43wJesj4+KN87MAOiQnUiVd9S8'
    b'o4YCIIltXB0hwmzDK5tVBO0V4jS8ckAwpub8TnCXAgCbd3DlJjaA+jNxmcMXN2xwR5eb2GsF'
    b'YdLAYxE5ysIAAAAASUVORK5CYII=')
index.append('OpenFolder')
catalog['OpenFolder'] = OpenFolder

#----------------------------------------------------------------------
OpenFolder_Big = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAATRJ'
    b'REFUWIXFl1GSgyAQRB+ae4WLJYy7F4OD7bIfqBE0kVWBrpqSwiqnnWkaUKrraYmuaXbg9uml'
    b'eT783geGr291ioHq+s0QEZ8DEfHvvpETO8nZDWvtKRKnkl9BItKAeT68MQb4X1vvdw1YgF3N'
    b'TJi1c/bv48gH4FXXX70MVXaIgP/98U18wDk7j5sQCJoJuMHLcLTWOOcYBVUseajASCLXcK4A'
    b'4EM+vAgemDSQL56j4ZxDRBCRtQaWE6Ww7Pty3KUTJWGMADAMEhOoUYG3mBzQWuuPO2B+iMgo'
    b'xkiE9dqQYiZQqw1a620CL4Moi1Wl452wvAamswMkGoD6fgDJZlRLiEsdVK/ACumJqJ4fbGgA'
    b'4tVQ+gmgllezcC6QA3U8BpGEAIRzWi0CquvVikBtNL+cNifwBy1MsjW3kRxnAAAAAElFTkSu'
    b'QmCC')
index.append('OpenFolder_Big')
catalog['OpenFolder_Big'] = OpenFolder_Big

#----------------------------------------------------------------------
Paste = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAALlJ'
    b'REFUOI2lk2EOgyAMRl9xB+vFljTZxerBZvcDGUxAt+xLNEj7PdpGRNLCP7qNNmN7RvstaZEZ'
    b'QCQtnQEgoiQMTA1QgDADMMAwy+ZiLGsza3LsDdlbsPw2cHfWFdxzpKxVtYFUNYAcUNVZuxxz'
    b'O0Bb5viBYwXdDD5h8yoGM+hPc9fOqup7/AFAOgPM5K7Edo/LCuqJ1djuxXaPE8C4jQpRwH6r'
    b'YKTprww2HGIF5wpkdhvLkK40BXyrF40kYP+GYnYkAAAAAElFTkSuQmCC')
index.append('Paste')
catalog['Paste'] = Paste

#----------------------------------------------------------------------
Paste_Big = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAPlJ'
    b'REFUWIXVl90OwiAMRr9uPlhfzIRkL8YezOEFVm0dAsuSjnPTjJ/OHgtRommGJ5Pr2wHcWhem'
    b'7ZH+zdM005EP4G6ApAdqFQrJrKLGukuG/A0ASAAQggwFFWVcKrcV2/HwTmTz5GhNuBv4OgVB'
    b'TUghMUYAwLrKs05gx5n5tV/y6byWKxoIaoFUdJz9vMJ1DZS6uT3avPu4G6jeA2UzveR9I9wD'
    b'tZiJkZtewBzN/kXNj2hAYh9ijDn3HE0LAWMa0Hy+Y43tEbsubfcEjGlAYqZ2Gn5NyHPOM6IB'
    b'TakHWnE30P2rWEy03oSWy/UA9f43lPN7FuMZOBt3A09nxGAurNE2QQAAAABJRU5ErkJggg==')
index.append('Paste_Big')
catalog['Paste_Big'] = Paste_Big

#----------------------------------------------------------------------
Redo = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAGpJ'
    b'REFUOI3tks0KwCAMg5t2r+0W8L3XXSb4j+Blhwk5JLYftQioyc7Rre5PAI7cXGdwsiyARkwJ'
    b'UBOoCUkXoSefJNLmue+GPaX7Gri8A2iE38HrfBnQay4A5LholL+jle8k57to9H/lfcADJhsm'
    b'5cIDIaYAAAAASUVORK5CYII=')
index.append('Redo')
catalog['Redo'] = Redo

#----------------------------------------------------------------------
Redo_Big = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAI9J'
    b'REFUWIXtlUEOgCAMBLfot9Wq/xYPphdMBSSxxHSuVN2dpEgUBlgSTL/uATyABwAwagfLPEUA'
    b'YH5+AYWdWgL0ZyBtnmsYj2te0OZlLj03N0Dpv0BLWkr6fM6QuQF1C96iNdf4n4HS5kJ/BmT/'
    b'meu2oba5YG7gdg8I0kiMrFvbna/Rr4GvMDfgATyAB/AAJ5A+MVQ7zuK2AAAAAElFTkSuQmCC')
index.append('Redo_Big')
catalog['Redo_Big'] = Redo_Big

#----------------------------------------------------------------------
Save = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAGRJ'
    b'REFUOI3Nk0sOgDAIRGcGD87F/SwMSrqoybjQl7BoQ1+gtKQC+7buMKCCqkXmvTmLyqlzgkGv'
    b'2BJUtbag8zNB5nlBs+j9A8AyGseEJyyBNYX+kDrfT4FUAID1oajgJXB53cIBvK4zQuA+3tIA'
    b'AAAASUVORK5CYII=')
index.append('Save')
catalog['Save'] = Save

#----------------------------------------------------------------------
Save_Big = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAI1J'
    b'REFUWIXtl0sOgCAMBV/Bg3NxxVWjIg1RYtvEzoaEBTwm/EqUMgCgbmuFIpQyAUDSnLTH0naU'
    b'cm056VvYLI/TmvZn4CukPWZuQC1AKce+MgkgEQEiQAQQb8LjTZh7JXtn/4xfA8xoBbP8x4A0'
    b'jn8DT2l/UKO/prmBCBABiCsjRqtCclMZ3QxoY24gAuwk5CRR8HiBvAAAAABJRU5ErkJggg==')
index.append('Save_Big')
catalog['Save_Big'] = Save_Big

#----------------------------------------------------------------------
Undo = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAGxJ'
    b'REFUOI3tklELgDAIhNX1twdX/W/tIaxhshF76SFhoMfuYx5jlkIzJVPuTwCW0QXTau0MEK3b'
    b'zpfAUugMEua9z1FzHbj11JAZI8T7Rwam1ViaJw4qDTHu/RrQg5hWAxqht2s8QBLs/5XnAQdM'
    b'DijlpP8ciAAAAABJRU5ErkJggg==')
index.append('Undo')
catalog['Undo'] = Undo

#----------------------------------------------------------------------
Undo_Big = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAJRJ'
    b'REFUWIXtlEsOgCAMBSl6bRT13tSFn4SfhSCpMX0bF606nUAB9KA4o1n/LgACIABKqbH1A+gM'
    b'PtWtPZ7LukGqzm4Awk14TQQ6TRxOnOsL+3MmvmvgbjgnpMxQyb3PboC8Ba2TU2E3UAyAziB1'
    b'57sC9Er1Jqw9E/Ee8OvsBqI98FbmyZ88Z+y/BkrDbkAABEAABGAHHBY4zsigTDIAAAAASUVO'
    b'RK5CYII=')
index.append('Undo_Big')
catalog['Undo_Big'] = Undo_Big

